"""Add invitations model

Revision ID: 16fd94beeb32
Revises: c8211a07bc11
Create Date: 2026-07-09 14:38:11.737369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16fd94beeb32'
down_revision: Union[str, None] = 'c8211a07bc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['persons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_table('expense_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'EXACT', 'PERCENTAGE', 'SHARES', name='split_type_enum'), nullable=False),
    sa.Column('split_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('expense_participants')
    role_enum = sa.Enum('ADMIN', 'MEMBER', name='roleenum')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('group_members', sa.Column('role', role_enum, nullable=False, server_default='MEMBER'))
    op.add_column('group_members', sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('group_members_group_id_fkey'), 'group_members', type_='foreignkey')
    op.drop_constraint(op.f('group_members_person_id_fkey'), 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_members', 'persons', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key(op.f('group_members_person_id_fkey'), 'group_members', 'persons', ['person_id'], ['id'])
    op.create_foreign_key(op.f('group_members_group_id_fkey'), 'group_members', 'groups', ['group_id'], ['id'])
    op.drop_column('group_members', 'joined_at')
    op.drop_column('group_members', 'role')
    role_enum = sa.Enum('ADMIN', 'MEMBER', name='roleenum')
    role_enum.drop(op.get_bind(), checkfirst=True)
    op.create_table('expense_participants',
    sa.Column('expense_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('expense_participants_expense_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('expense_participants_person_id_fkey')),
    sa.PrimaryKeyConstraint('expense_id', 'person_id', name=op.f('expense_participants_pkey'))
    )
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
