"""añadidos campos email y password a person

Revision ID: 23db415e48d4
Revises: ff0034959e65
Create Date: 2026-07-06 09:41:11.477226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23db415e48d4'
down_revision: Union[str, None] = 'ff0034959e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('email', sa.String(), nullable=False))
    op.add_column('persons', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_persons_email'), 'persons', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_email'), table_name='persons')
    op.drop_column('persons', 'password_hash')
    op.drop_column('persons', 'email')
    # ### end Alembic commands ###
