"""Add audit log

Revision ID: 840b8921bb77
Revises: 16fd94beeb32
Create Date: 2026-07-09 16:32:22.578237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '840b8921bb77'
down_revision: Union[str, None] = '16fd94beeb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='audit_action_enum'), nullable=False),
    sa.Column('entity_type', sa.Enum('EXPENSE', 'GROUP_MEMBER', 'CATEGORY', name='entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color_hex', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('expenses', sa.Column('category_id', sa.String(), server_default='general', nullable=False))
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.VARCHAR(), server_default='general', autoincrement=False, nullable=False))
    op.drop_column('expenses', 'category_id')
    op.drop_table('custom_categories')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
