"""feat: añadir categoria a los gastos

Revision ID: c8211a07bc11
Revises: ab4e58d3658e
Create Date: 2026-07-06 11:31:41.147668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8211a07bc11'
down_revision: Union[str, None] = 'ab4e58d3658e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'category')
    # ### end Alembic commands ###
